ecmaVersion: 6

libs:
  - browser

loadEagerly:
  - src/script/*.js
  - src/script/**/*.js

dontLoad:
  - node_modules/**

plugins:
  modules: {}
  es_modules: {}
  node: {}

  doc_comment:
    fullDocs: true
    strong: true
